stages:
  - deploy-backend
  - deploy-frontend

variables:
  GCP_PROJECT_ID: "$GCP_PROJECT_ID"
  GCP_REGION: "$GCP_REGION"
  BACKEND_SERVICE: "ofv-backend"
  FRONTEND_SERVICE: "ofv-frontend"

.gcloud_auth: &gcloud_auth |
  echo "$GCP_SA_KEY" | base64 -d > ${CI_PROJECT_DIR}/gcp-key.json
  gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
  gcloud config set project "$GCP_PROJECT_ID"
  gcloud config set run/platform managed
  gcloud config set run/region "$GCP_REGION"

deploy-backend:
  stage: deploy-backend
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - *gcloud_auth
    - gcloud run deploy "$BACKEND_SERVICE" --source backend --allow-unauthenticated --quiet
    - echo "BACKEND_URL=$(gcloud run services describe $BACKEND_SERVICE --region $GCP_REGION --format 'value(status.url)')" > backend_url.env
  artifacts:
    reports:
      dotenv: backend_url.env

deploy-frontend:
  stage: deploy-frontend
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  needs:
    - job: deploy-backend
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - *gcloud_auth
    - |
      if [ -z "$BACKEND_URL" ]; then
        echo "BACKEND_URL not set from previous job; aborting" && exit 1
      fi
    - gcloud run deploy "$FRONTEND_SERVICE" --source frontend --allow-unauthenticated --set-env-vars BACKEND_URL="$BACKEND_URL" --quiet


